Introduce GitHub Actions PR Check workflow, fixes JBIDE-27695
jbdevstudio/jbdevstudio-product pull request #563
Opened 2021-03-30 20:30 UTC by odockal

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

2021-04-28 11:47 UTC, odockal commented
@sbouchet review please.

2021-04-28 14:42 UTC, sbouchet requested changes

2021-04-28 14:42 UTC, sbouchet commented on .github/workflows/build_test.yml
> +        ref: ${{ github.event.pull_request.head.sha }}
please add fetch-depth: 0 to avoid baseline errors

2021-04-28 14:42 UTC, sbouchet commented on .github/workflows/build_test.yml
> +        run: mvn clean verify --settings build-ci/maven-settings.xml --quiet
--quiet is difficult to review when failing. please use only --no-transfer-progress

2021-04-29 15:21 UTC, sbouchet approved these changes
LGTM

2021-04-29 20:48 UTC, merged